# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrNurfTpfSfW9MXCIbkywSP7FbFViMhX
"""

import pandas as pd
df = pd.read_csv('salaries_by_college_major.csv')
df.head()

import pandas as pd
df = pd.read_csv('salaries_by_college_major.csv')
df.head()

df.shape

df.columns

df.isna

df.tail()

df.isna()

df.tail()

clean_df = df.dropna()
clean_df.tail()

clean_df['Starting Median Salary'].max()

clean_df['Starting Median Salary'].idxmax()

clean_df['Undergraduate Major'].loc[43]

clean_df['Undergraduate Major'][43]

clean_df.loc[43]

highest_mid_salary = clean_df['Mid-Career Median Salary'].max()

print(highest_mid_salary)

highest_mid_salary = clean_df['Mid-Career Median Salary'].max()

highest_mid_salary = clean_df['Mid-Career Median Salary'].max()
index = clean_df['Mid-Career Median Salary'].idxmax()

highest_mid_salary = clean_df['Mid-Career Median Salary'].max()
index = clean_df['Mid-Career Median Salary'].idxmax()
print(highest_mid_salary, index)

clean_df['Undergraduate Major'][8]

lowest_start = clean_df['Starting Median Salary'].min()
major = clean_df['Undergraduate Major'].loc[clean_df['Starting Median Salary'].idxmin()]

lowest_start = clean_df['Starting Median Salary'].min()
major = clean_df['Undergraduate Major'].loc[clean_df['Starting Median Salary'].idxmin()]
print(lowest_start, major)

clean_df.loc[clean_df['Mid-Career Median Salary'].idxmin()]

spread_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']
clean_df.insert(1, 'Spread', spread_col)
clean_df.head()

low_risk = clean_df.sort_values('Spread')
low_risk[['Undergraduate Major', 'Spread']].head()

highest_potential = clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False)
highest_potential[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

highest_spread = clean_df.sort_values('Spread', ascending=False)
highest_spread[['Undergraduate Major', 'Spread']].head()

highest_spread = clean_df.sort_values('Mid-Career Median Salary', ascending=False)
highest_spread[['Undergraduate Major', 'Mid-Career Median Salary']].head()

clean_df.groupby("Group").count()

clean_df.groupby("Group").mean()

pd.options.display.float_format = '{:,.2f}'.format
clean_df.groupby("Group").mean()

